version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    container_name: "${PROJECT_NAME}_app"
    environment:
      CONFIG_FILE: /home/app/config.yml
    image: "$PROJECT_NAME"
    volumes:
      - ../:/home/app
    working_dir: /home/app
